version: '3.8'

services:
  java-app:
    build:
      context: . # Current directory
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: "-Xmx1G -Xms512M" # Adjust memory settings if needed
    container_name: waze-api-client
    tty: true